os:
  - osx

language: node_js

node_js:
  - '8'

before_script:
  - "xvfb-run -a"
  - sleep 3 # give xvfb some time to start
  - cd src

script:
  - npm install
  - npm test

cache:
  directories:
    - src/node_modules
